// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres.espqunmnwjthycvsyibb:Z.RDn9zEAZ3DW_S@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
  },
});
